### ISSUE TITLE
Exclude certatin notes in the path-finder? 

### ISSUE THREAD

**Issue by zhixiangCai** [jerrywcy/obsidian-path-finder#2]
**Is your feature request related to a problem? Please describe.**
Could you add a feature that users can exclude certatin notes in the path-finder? Such as dailynotes?

**Describe the solution you'd like**
Obsidian's deafult graph can exclude certain notes in its graph view, you can check in the settings "Settings =>Files&Links =>Excluded files"

**Comment by jerrywcy** [comment]
First sorry for not replying for such a long time...
Good news is that this should be a simple feature and I will try to add it after my exam on 2.27

**Comment by jerrywcy** [comment]
@zhixiangCai This feature is added in v1.1.6. Please open an issue if you face any problems when using.
Again apologize for my laziness... This could have been done within two days but I put it off until now...
